SELECT EXTERNAL_EVENT_NUMBER, * FROM ACTIVITIES
/*
sp_help ACTIVITIES
select IDENT_CURRENT('ACTIVITIES')
SELECT ACTIVITYNUMBER, count(*) as N FROM ACTIVITIES group by ACTIVITYNUMBER order by n desc
SELECT * FROM ACTIVITIES order by cast (ACTIVITYNUMBER as int)
*/