SELECT * FROM CUSTOMERS ORDER BY CUSTOMER_ID DESC
SELECT * FROM ARTRANSACTIONS ORDER BY ARTRANSACTION_ID DESC
SELECT * FROM RECEIPTPAYMENTS ORDER BY RECEIPTPAYMENT_ID DESC
SELECT * FROM SYSTEM_USERS
SELECT * FROM RESOURCESCHEDULERUSERSETTINGS

select * from sys.tables where name like '%USER%'


SELECT* FROM TRANSACTIONS ORDER BY TRANSACTION_ID DESC

