SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID = 623544 --Charles T Burns
SELECT * FROM CUSTOMER_ALTERNATE_KEYS WHERE CUSTOMER_ID = 623544

SELECT * FROM ALTERNATE_KEY_STATUSES ORDER BY ALTERNATE_KEY_STATUS
SELECT * FROM ALTERNATE_KEY_TYPES ORDER BY ALTERNATE_KEY_TYPE
SELECT * FROM ALTKEYTYPE_ALTKEYSTATUSES ORDER BY ALTERNATEKEYTYPE_ID
