SELECT * FROM DCPROGRAMS WHERE DCPROGRAM_ID = 5

SELECT * FROM DCSESSIONS WHERE DCSESSION_ID = 8
SELECT * FROM DCSESSIONDATES WHERE DCSESSION_ID = 8
SELECT * FROM DCPROGRAMSESSIONS WHERE DCSESSION_ID = 8
SELECT * FROM DCREGISTRATIONS WHERE DCPROGRAM_ID = 5 AND DCSESSION_ID = 8

SELECT T.DCPROGRAM_ID, T.RECEIPTHEADER_ID, T.* FROM TRANSACTIONS T INNER JOIN DCREGISTRATIONS D ON T.TRANSACTION_ID = D.LASTTRANSACTION_ID WHERE D.DCPROGRAM_ID = 5 AND D.DCSESSION_ID = 8

SELECT DD.BEGDATETIME, DR.* FROM DCREGISTRATIONS DR INNER JOIN DCSESSIONDATES DD ON DR.DCSESSIONDATE_ID = DD.DCSESSIONDATE_ID WHERE DCPROGRAM_ID = 5 AND DR.DCSESSION_ID = 8 AND DR.CUSTOMER_ID = 160
SELECT DD.BEGDATETIME, DR.* FROM DCREGISTRATIONS DR INNER JOIN DCSESSIONDATES DD ON DR.DCSESSIONDATE_ID = DD.DCSESSIONDATE_ID WHERE DCPROGRAM_ID = 5 AND DR.DCSESSION_ID = 8 AND DR.CUSTOMER_ID = 161

SELECT DATEDIFF(day, '20150901', CAST('20151231' AS smalldatetime))

