/* Codes in
	GiftCertificateBO.java
	GiftCertificateTypeBO.java
*/
--Gift Card
SELECT * FROM GIFT_CERTIFICATES ORDER BY GIFT_CERTIFICATE_ID DESC
SELECT * FROM GIFT_CERTIFICATES WHERE CUSTOMER_ID = 69
SELECT * FROM GIFT_CERTIFICATES WHERE GIFT_CERTIFICATE_NUMBER = '4071772197968013'
SELECT  PURCHASED_AMOUNT, AVAILABLE_AMOUNT, REDEEMED_AMOUNT, DATE_LAST_USED, * FROM GIFT_CERTIFICATES WHERE GIFT_CERTIFICATE_NUMBER = '4071772197968013'

--Gift Card Type
SELECT * FROM GIFT_CERTIFICATE_TYPES
SELECT * FROM GIFT_CERTIFICATE_TYPE_SITES

--Transactions
SELECT GIFT_CERTIFICATE_ID, * FROM TRANSACTIONS where GIFT_CERTIFICATE_ID = 59
