SELECT INTERNETSITE_ID, * FROM SYSTEM
SELECT * FROM PROFILES WHERE NAME='Internet Profile'
SELECT * FROM SYSTEM_USERS WHERE PROFILE_ID = 9

--SystemUser.internetUser()
--top 1
SELECT * FROM SYSTEM_USERS
WHERE PROFILE_ID= (SELECT PROFILE_ID FROM PROFILES WHERE NAME='Internet Profile')
	AND SITE_ID=(SELECT INTERNETSITE_ID FROM SYSTEM)
