DECLARE @receiptheader_id int
SELECT @receiptheader_id = RECEIPTHEADER_ID FROM RECEIPTHEADERS WHERE RECEIPTNUMBER =  3000020.005
SELECT * FROM RECEIPTHEADERS where RECEIPTHEADER_ID = @receiptheader_id
SELECT APPLIED_AMOUNT, * FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id
SELECT AMOUNT, APPLIEDAMOUNT, * FROM RECEIPTDETAILS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id) ORDER BY RECEIPTDETAIL_ID
SELECT PAYMENTAMOUNT, * FROM RECEIPTPAYMENTS WHERE RECEIPTHEADER_ID = @receiptheader_id
--SELECT * FROM GL_LEDGER WHERE RECEIPTDETAIL_ID IN (SELECT RECEIPTDETAIL_ID FROM RECEIPTDETAILS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id)) ORDER BY GL_LEDGER_ID
--SELECT * FROM ARSCHEDULEHEADER WHERE RECEIPTPAYMENT_ID = (SELECT RECEIPTPAYMENT_ID FROM RECEIPTPAYMENTS WHERE RECEIPTHEADER_ID = @receiptheader_id)
SELECT RECEIPTNUMBER_PLAN = (
		SELECT RECEIPTNUMBER
		FROM RECEIPTHEADERS H
			INNER JOIN RECEIPTPAYMENTS P ON P.RECEIPTHEADER_ID = H.RECEIPTHEADER_ID
			INNER JOIN ARSCHEDULEHEADER AH ON AH.RECEIPTPAYMENT_ID = P.RECEIPTPAYMENT_ID
		WHERE AH.ARSCHEDULEHEADER_ID = ARTRANSACTIONS.ARSCHEDULEHEADER_ID
	)
	, AMOUNT, * FROM ARTRANSACTIONS WHERE RECEIPTHEADER_ID = @receiptheader_id
