SELECT * FROM STAGES
SELECT * FROM STAGESEQUENCES
SELECT * FROM STAGESEQUENCESTAGES
SELECT * FROM STAGESEQUENCESTAGEDETAILS

SELECT * FROM TRANSACTIONSTAGES
SELECT * FROM TRANSACTIONSTAGEDETAILS


select * from sys.indexes where object_id = OBJECT_ID('TRANSACTIONSTAGES')

sp_helpindex TRANSACTIONSTAGES

create index TRANSACTIONSTAGES__STAGE_ID_Jesse2 on TRANSACTIONSTAGES(STAGE_ID)