SELECT * FROM USAGE_FEES

--SP_HELP USAGE_FEES

SELECT USAGE_FEE_ID, * FROM PACKAGES WHERE PACKAGE_ID = 17
SELECT * FROM PACKAGE_USAGE_FEE_PERIODS

-- Check membership usage fee
DECLARE @USAGE_FEE_ID int = 2, @CUSTOMER_ID int = 196
SELECT *
FROM DBO.USAGE_FEE_TRANSACTIONS uft
	JOIN DBO.MEMBERSHIPS m ON uft.MEMBERSHIP_ID = m.MEMBERSHIP_ID
	LEFT JOIN DBO.TRANSACTIONS t ON t.MEMBERSHIP_ID = m.MEMBERSHIP_ID AND t.TRANSACTIONTYPE=30
WHERE uft.USAGE_FEE_ID=@USAGE_FEE_ID
	AND uft.VOIDED = 0
	AND m.STATUS IN (1, 4, 5)
	AND m.PRIMARYMEMBERCUSTOMER_ID IN (@CUSTOMER_ID)

select * from USAGE_FEE_TRANSACTIONS

