SELECT * FROM BULKEMAILTASKS WHERE DATESTAMP > '20150731'
SELECT BULKEMAILTASK_ID, SUBJECT ,DATESTAMP FROM BULKEMAILTASKS WHERE DATESTAMP > '20150731'

SELECT TOP 500 T.DATESTAMP, R.ERRORMESSAGE, R.BULKEMAILRECIPIENT_ID, R.BULKEMAILTASK_ID, R.CUSTOMER_ID, R.CUSTOMERNAME, R.CUSTOMEREMAIL, R.STATUS, R.TIMESTARTED
FROM BULKEMAILRECIPIENTS R INNER JOIN BULKEMAILTASKS T ON R.BULKEMAILTASK_ID = T.BULKEMAILTASK_ID WHERE T.DATESTAMP BETWEEN '20150731 3:21 PM' AND '20150731 3:22 PM'
ORDER BY R.BULKEMAILRECIPIENT_ID

SELECT KeyWordValue FROM SYSTEMINFO WHERE KEYWORD LIKE 'Image_Storage_Path'


select UPLOADEDFILES.UploadedFile_id, UPLOADEDFILES.DisplayName, UPLOADEDFILES.ContentType
from BULKEMAILATTACHMENTS, UPLOADEDFILES
where BULKEMAILATTACHMENTS.UploadedFile_id = UPLOADEDFILES.UploadedFile_id and BULKEMAILATTACHMENTS.BulkEmailTask_id = 2067


select top 10 * from ActiveNetSites.dbo.APPLICATION_LOG

select RECNETSTARTTIME, RECNETFINISHTIME, * from RSERVERLOG where RSERVERSTARTTIME between '20150731 15:21' and '20150731 15:22'

select * from REPORTDEFINITION

--CITY OF BETTENDORF IA, ANE-33012
SELECT TOP 500 * FROM BULKEMAILRECIPIENTS WHERE BULKEMAILTASK_ID IN (2015, 2016) ORDER BY BULKEMAILRECIPIENT_ID