--USE mscractivenet --US10
/*
select TOP 100 * from BULKEMAILTASKS (NOLOCK) WHERE BULKEMAILTASK_ID > 86 ORDER BY BULKEMAILTASK_ID DESC
*/
select A.*, U.* from BULKEMAILATTACHMENTS A (NOLOCK) LEFT JOIN UPLOADEDFILES U ON A.UPLOADEDFILE_ID = U.UPLOADEDFILE_ID WHERE BulkEmailTask_id >= 0

SELECT T.DATESTAMP, T.BULKEMAILTASK_ID, T.BULKEMAILTASKNAME, T.STATUS, T.SUBJECT, T.SCHEDULED_DATETIME
	, A.SCHEDULED_REPORT_FILENAME, A.UPLOADEDFILE_ID
	, R.BULKEMAILRECIPIENT_ID, R.CUSTOMER_ID, R.CUSTOMERNAME, R.CUSTOMEREMAIL, R.STATUS AS ReciStatus, R.ERRORMESSAGE
FROM BULKEMAILTASKS T
	LEFT JOIN BULKEMAILATTACHMENTS A ON A.BULKEMAILTASK_ID = T.BULKEMAILTASK_ID
	OUTER APPLY (SELECT TOP 3 * FROM BULKEMAILRECIPIENTS R1 WHERE R1.BULKEMAILTASK_ID = T.BULKEMAILTASK_ID) R
WHERE T.DATESTAMP BETWEEN '2016-03-01 10:19' AND '2016-03-24 10:25'
ORDER BY R.BULKEMAILRECIPIENT_ID DESC


select * from RSERVERLOG where RSERVERSTARTTIME between '2016-03-14 10:19' AND '2016-03-14 10:25'