--==================================================================================================================
-- CRT BY:	  Jesse Wei
-- CRT DT:	  07/20/2015
--
-- Description: ANE-32203 INC2295093 - A/R Sumamry report showing customer creditd in A/R column, but customers do not have a credit on account
--
--==================================================================================================================
Use Marana

SET XACT_ABORT ON

BEGIN TRANSACTION

IF EXISTS(SELECT GL_LEDGER_ID, GLACCOUNT_ID, ARSCHEDULEHEADER_ID FROM GL_LEDGER WHERE ARSCHEDULEHEADER_ID IS NOT NULL AND GL_LEDGER_ID IN (108503)) BEGIN
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (108503)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (110679, 110681)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (110885, 110887)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (109734)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (108817)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (109039)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (109934)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (109922)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (110671)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (110182)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (110266, 110638)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (107433)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (107347)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (108200)
	UPDATE GL_LEDGER SET GLACCOUNT_ID = 16, ARSCHEDULEHEADER_ID = NULL WHERE GL_LEDGER_ID IN (110341)

	DELETE FROM GL_LEDGER_LOG WHERE LEFT(DESCRIPTION, 9) = 'ANE-32203'

	PRINT char(10) + 'Rollback is done'
END
ELSE BEGIN
	PRINT 'Nothing is rolled back. Data does not pass data validation.'
END

COMMIT TRANSACTION