USE Org_DB

SET XACT_ABORT ON

DECLARE @subject varchar(max)		= 'ANE-100XXX Add an Overpayment to receipt in which charge is missing.'
DECLARE @author varchar(max)		= 'Susan Huai'
DECLARE @created_date datetime		= '4/24/2019'
DECLARE @type varchar(max)			= 'Rollback' --Datafix or Rollback
DECLARE @description varchar(max)	= 'add $28 over payment transaction to receipt #1514141.001' --Put additional information if necessary.
DECLARE @org varchar(100) = DB_NAME()
DECLARE @return int
EXEC @return = rollbackdb.dbo.audit_datafix @org, @subject, @author, @created_date, @type, @description
IF @@ERROR > 0 OR @return = -1 RETURN

IF NOT EXISTS(SELECT 1 FROM ROLLBACKDB.sys.tables WHERE name = 'ANE_100XXX_OVERPAYMENT_DEL_20190424')
	BEGIN
	PRINT 'DATA FIX WAS NOT APPLIED. ABORT.'
	SET NOEXEC ON;
	RETURN
	END

DECLARE @rollback_sql NVARCHAR(MAX) = ''

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET XACT_ABORT ON

BEGIN TRANSACTION

SELECT @rollback_sql= CONCAT(@rollback_sql, DML, TABLENAME, KEYVALUE, WHERECONDITION, CHAR(10))
FROM ROLLBACKDB.DBO.ANE_100XXX_OVERPAYMENT_DEL_20190424
ORDER BY ROLLBACKORDER DESC

EXEC(@rollback_sql)

UPDATE TRANSACTIONS SET CREDIT_CARD_AMOUNT=56 WHERE TRANSACTION_ID=6761762 AND RECEIPTHEADER_ID=3487431
UPDATE RECEIPTDETAILS SET CREDIT_CARD_AMOUNT=56 WHERE RECEIPTDETAIL_ID=8665304 AND TRANSACTION_ID=6761762

UPDATE RECEIPTHEADERS
SET  RECEIPT_DETAIL_PAYMENT_GENERATED='1899-12-30 00:00:00', AGENCY_RECEIPT_DETAIL_GENERATED='1899-12-30 00:00:00'
WHERE RECEIPTHEADER_ID=3487431 AND RECEIPTNUMBER='1514141.001'

PRINT char(10) + 'Rollback is done.'

DROP TABLE ROLLBACKDB.DBO.ANE_100XXX_OVERPAYMENT_DEL_20190424

COMMIT TRANSACTION

