--use uregina
SELECT c.CUSTOMER_ID, c.FIRSTNAME, c.LASTNAME, h.RECEIPTNUMBER, h.RECEIPTHEADER_ID, ah.*
FROM ARSCHEDULEHEADER ah
	inner join DBO.RECEIPTPAYMENTS rp on ah.receiptpayment_id = rp.receiptpayment_id
	inner join RECEIPTHEADERS h on h.RECEIPTHEADER_ID = rp.RECEIPTHEADER_ID
	inner join customers c on ah.customer_id = c.customer_id
WHERE 1=1
	AND SUSPEND_AUTO_PAY = 0
	AND AUTO_PAYMENT_TYPE IN (1,2,3) AND AUTO_PAYMENT_STATUS IN (0, 10, 11)
	AND ARSCHEDULEHEADER_ID IN (
		SELECT H.ARSCHEDULEHEADER_ID
		FROM (
				SELECT DISTINCT ARSCHEDULEHEADER_ID FROM ARSCHEDULEDETAIL WHERE DATEDUE = '20180301'
			) H
			LEFT JOIN (
				SELECT ARSCHEDULEHEADER_ID, SUM(AMOUNTDUE) AMOUNT_FUTURE FROM ARSCHEDULEDETAIL
				WHERE DATEDUE > '20180301'
				GROUP BY ARSCHEDULEHEADER_ID
			) AS S ON S.ARSCHEDULEHEADER_ID = H.ARSCHEDULEHEADER_ID
			LEFT JOIN (
				SELECT ARSCHEDULEHEADER_ID, SUM(AMOUNT) AS AMOUNT_DUE FROM ARTRANSACTIONS
				WHERE DATESTAMP <= '20180301 4:00' --We think auto-charge completed before 4:00 AM.
				GROUP BY ARSCHEDULEHEADER_ID
			) AS T ON T.ARSCHEDULEHEADER_ID = H.ARSCHEDULEHEADER_ID
		WHERE ISNULL(S.AMOUNT_FUTURE, 0) < ISNULL(T.AMOUNT_DUE, 0)
		--UNION SELECT ARSCHEDULEHEADER_ID FROM ARSCHEDULEHEADER WHERE ARSCHEDULEHEADER_ID IN (11599, 11744, 11918) --Schedules that finish on target date (@date).
	)
order by c.CUSTOMER_ID, ah.ARSCHEDULEHEADER_ID

