DECLARE @receiptnumber money
DECLARE @receiptheader_id int
DECLARE @transaction_id int
SET @receiptnumber = 1000214.001
SET @receiptheader_id = (SELECT RECEIPTHEADER_ID FROM RECEIPTHEADERS WHERE RECEIPTNUMBER = @receiptnumber)
SELECT transactionfee, CONVENIENCEFEE, CONV_FEE_ABSORBED, CONV_FEE_SURCHARGE, * FROM RECEIPTHEADERS where RECEIPTHEADER_ID = @receiptheader_id
SELECT TRANSACTION_FEE, CONVENIENCE_FEE, ABSORBED_CONVENIENCE_FEE, APPLIED_AMOUNT, * FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id
SELECT TRANSACTION_FEE, CONVENIENCE_FEE, ABSORBED_CONVENIENCE_FEE, * FROM RECEIPTDETAILS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id) ORDER BY RECEIPTDETAIL_ID
SELECT CONVENIENCEFEE, PAYMENTAMOUNT, * FROM RECEIPTPAYMENTS WHERE RECEIPTHEADER_ID = @receiptheader_id