DECLARE @receiptnumber money
DECLARE @receiptheader_id int
DECLARE @transaction_id int
SET @receiptnumber = 1000302.002
SET @receiptheader_id = (SELECT RECEIPTHEADER_ID FROM RECEIPTHEADERS WHERE RECEIPTNUMBER = @receiptnumber)
SELECT * FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id
SELECT * FROM RECEIPTDETAILS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id) ORDER BY RECEIPTDETAIL_ID
SELECT * FROM RECEIPTPAYMENTS WHERE RECEIPTHEADER_ID = @receiptheader_id

SELECT GL.GL_LEDGER_ID, GL.RECEIPTDETAIL_ID, GL.GLACCOUNT_ID, GL.AMOUNT, GL.ADJUSTED_AMOUNT, GL.IS_INCOME_ACCOUNT, GA.ACCOUNTNAME, GL.DATESTAMP
FROM GL_LEDGER GL INNER JOIN GLACCOUNTS GA ON GL.GLACCOUNT_ID = GA.GLACCOUNT_ID
WHERE GL.RECEIPTDETAIL_ID IN (SELECT RECEIPTDETAIL_ID FROM RECEIPTDETAILS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id))

/*
1 = Asset, 2 = Liability, 3 = Income, 4 = Capital, 5 = Expense
SELECT * FROM GLACCOUNTS
SELECT * FROM GL_LEDGER WHERE DATESTAMP BETWEEN GETDATE() - 1 AND GETDATE()

update SYSTEMINFO set KEYWORDVALUE = 'true' where KEYWORD ='shorten_thread_timeouts'
*/
