SELECT ISNULL(MAX(ARTRANSACTIONS.ARSCHEDULEHEADER_ID),0) AS ARSCHEDULEHEADER_ID INTO #aging_customer_t
FROM ARTRANSACTIONS "ARTRANSACTIONS" JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID JOIN CUSTOMERS CUSTOMERS ON ARTRANSACTIONS.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID
WHERE ARTRANSACTIONS.VOIDED = 0 AND ARTRANSACTIONS_1.VOIDED = 0 AND ARTRANSACTIONS.COMPANY_ID IS NULL
	AND EXISTS(SELECT * FROM ARTRANSACTIONS ART WHERE ART.ARSCHEDULEHEADER_ID = ARTRANSACTIONS.ARSCHEDULEHEADER_ID AND ART.VOIDED = 0 GROUP BY ART.ARSCHEDULEHEADER_ID HAVING SUM(ART.AMOUNT) > 0)
GROUP BY ARTRANSACTIONS.ARSCHEDULEHEADER_ID HAVING SUM(ARTRANSACTIONS.AMOUNT) > 0

SELECT ISNULL(MAX(ARTRANSACTIONS.ARSCHEDULEHEADER_ID),0) AS ARSCHEDULEHEADER_ID INTO #aging_company_t
FROM ARTRANSACTIONS "ARTRANSACTIONS" JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID JOIN COMPANIES COMPANIES ON ARTRANSACTIONS.COMPANY_ID=COMPANIES.COMPANY_ID
WHERE ARTRANSACTIONS.VOIDED = 0 AND ARTRANSACTIONS_1.VOIDED = 0
	AND EXISTS(SELECT * FROM ARTRANSACTIONS ART WHERE ART.ARSCHEDULEHEADER_ID = ARTRANSACTIONS.ARSCHEDULEHEADER_ID AND ART.VOIDED = 0 GROUP BY ART.ARSCHEDULEHEADER_ID HAVING SUM(ART.AMOUNT) > 0)
GROUP BY ARTRANSACTIONS.ARSCHEDULEHEADER_ID HAVING SUM(ARTRANSACTIONS.AMOUNT) > 0


SELECT (1) AS CLIENTTYPE, ARSCHEDULEHEADER.CUSTOMER_ID AS ID, (CUSTOMERS.LASTNAME + CUSTOMERS.FIRSTNAME) AS CUSTOMERNAME, (CUSTOMERS.LASTNAME + CUSTOMERS.FIRSTNAME) AS SORTNAME
	, CREDITONACCOUNT = ((SELECT SUM(AMOUNT) AS AMOUNT FROM CUSTOMERACCOUNTS WHERE  CUSTOMERACCOUNTS.CUSTOMER_ID = ARSCHEDULEHEADER.CUSTOMER_ID AND (CUSTOMERACCOUNTS.VOIDED = 0)) + (SELECT ISNULL(SUM(LC.LINKED_AMOUNT),0) FROM LINKEDCREDITS LC LEFT JOIN ARTRANSACTIONS ART ON ART.ARTRANSACTION_ID=LC.ARTRANSACTION_ID LEFT JOIN RECEIPTHEADERS RH ON RH.RECEIPTHEADER_ID=ART.RECEIPTHEADER_ID LEFT JOIN CUSTOMERACCOUNTS CA ON LC.CUSTOMERACCOUNT_ID=CA.CUSTOMERACCOUNT_ID WHERE LC.CUSTOMER_ID=ARSCHEDULEHEADER.CUSTOMER_ID AND (CA.CUSTOMERACCOUNT_ID IS NULL OR CA.CUSTOMER_ID=ARSCHEDULEHEADER.CUSTOMER_ID) AND UNLINKED=0))
	, AMOUNTLINKED = (SELECT SUM(LINKEDCREDITS.LINKED_AMOUNT) AS AMOUNTLINKED FROM LINKEDCREDITS JOIN ARSCHEDULEHEADER ARH ON ARH.ARSCHEDULEHEADER_ID = LINKEDCREDITS.ARSCHEDULEHEADER_ID WHERE LINKEDCREDITS.CUSTOMER_ID = ARSCHEDULEHEADER.CUSTOMER_ID AND LINKEDCREDITS.UNLINKED=0 AND ARH.COMPANY_ID IS  NULL)
	, ARSCHEDULE_AMOUNTLINKED = (SELECT SUM(LINKEDCREDITS.LINKED_AMOUNT) AS AMOUNTLINKED FROM LINKEDCREDITS JOIN ARSCHEDULEHEADER ARH ON ARH.ARSCHEDULEHEADER_ID = LINKEDCREDITS.ARSCHEDULEHEADER_ID WHERE LINKEDCREDITS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND LINKEDCREDITS.UNLINKED=0)
	, CREDITONACCOUNT = ((SELECT SUM(CUSTOMERACCOUNTS.AMOUNT) FROM CUSTOMERACCOUNTS WHERE CUSTOMERACCOUNTS.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID AND ((CUSTOMERACCOUNTS.EXPIRATIONDATE = {TS '1899-12-30 00:00:00'} OR CUSTOMERACCOUNTS.EXPIRATIONDATE >= {TS '2015-09-30 15:29:42'}) AND CUSTOMERACCOUNTS.VOIDED=0)) + (SELECT ISNULL(SUM(LC.LINKED_AMOUNT),0) FROM LINKEDCREDITS LC LEFT JOIN ARTRANSACTIONS ART ON ART.ARTRANSACTION_ID=LC.ARTRANSACTION_ID LEFT JOIN RECEIPTHEADERS RH ON RH.RECEIPTHEADER_ID=ART.RECEIPTHEADER_ID LEFT JOIN CUSTOMERACCOUNTS CA ON LC.CUSTOMERACCOUNT_ID=CA.CUSTOMERACCOUNT_ID WHERE LC.CUSTOMER_ID=ARSCHEDULEHEADER.CUSTOMER_ID AND (CA.CUSTOMERACCOUNT_ID IS NULL OR CA.CUSTOMER_ID=ARSCHEDULEHEADER.CUSTOMER_ID) AND UNLINKED=0))
	, CUSTOMERS.RETIRED AS RETIRED, ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID, ARSCHEDULEDETAIL.DATEDUE AS DATEDUE
	, TOTALDUE = (CASE WHEN ARSCHEDULEDETAIL.INITIALPAYMENT <> 0 THEN ARSCHEDULEDETAIL.AMOUNTDUE+ISNULL((SELECT SUM(ARD.AMOUNTDUE) FROM ARSCHEDULEDETAIL ARD WHERE ARD.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND ARD.VOIDED = 0 AND ARD.INITIALPAYMENT = 0 AND ARD.AMOUNTDUE < 0),0) ELSE ARSCHEDULEDETAIL.AMOUNTDUE  END)
	, ARSCHEDULEHEADER.NUMBEROFPAYMENTS, ARSCHEDULEDETAIL.ARSCHEDULEDETAIL_ID, ARSCHEDULEHEADER.AUTO_PAYMENT_CC_EXP, ARSCHEDULEDETAIL.INITIALPAYMENT
FROM ARSCHEDULEHEADER
	JOIN ARSCHEDULEDETAIL ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARSCHEDULEDETAIL.ARSCHEDULEHEADER_ID
	JOIN ARTRANSACTIONS ARTRANSACTIONS ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARTRANSACTIONS.ARSCHEDULEHEADER_ID
	JOIN CUSTOMERS CUSTOMERS ON ARSCHEDULEHEADER.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID AND ARSCHEDULEHEADER.COMPANY_ID IS NULL
WHERE ARSCHEDULEHEADER.CUSTOMER_ID IN (147)
	AND (ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID IN (SELECT ARSCHEDULEHEADER_ID FROM #AGING_CUSTOMER_T))
	AND ARSCHEDULEHEADER.VOIDED = 0 AND ARSCHEDULEDETAIL.VOIDED = 0 AND (ARSCHEDULEDETAIL.AMOUNTDUE > 0)
	AND (
		ARSCHEDULEHEADER.AMOUNT
			- (
				SELECT CASE WHEN SUM(LINKEDCREDITS.LINKED_AMOUNT) IS NULL THEN 0 ELSE SUM(LINKEDCREDITS.LINKED_AMOUNT) END AS AMOUNTLINKED FROM LINKEDCREDITS
				WHERE LINKEDCREDITS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND LINKEDCREDITS.UNLINKED=0
			)
	) <> 0
UNION
SELECT (2) AS CLIENTTYPE, ARSCHEDULEHEADER.COMPANY_ID AS ID, COMPANIES.COMPANYNAME AS CUSTOMERNAME, COMPANIES.COMPANYNAME AS SORTNAME, ((SELECT SUM(AMOUNT) AS AMOUNT FROM CUSTOMERACCOUNTS WHERE  CUSTOMERACCOUNTS.COMPANY_ID = ARSCHEDULEHEADER.COMPANY_ID AND (CUSTOMERACCOUNTS.VOIDED = 0)) + (SELECT ISNULL(SUM(LC.LINKED_AMOUNT),0) FROM LINKEDCREDITS LC LEFT JOIN ARTRANSACTIONS ART ON ART.ARTRANSACTION_ID=LC.ARTRANSACTION_ID LEFT JOIN RECEIPTHEADERS RH ON RH.RECEIPTHEADER_ID=ART.RECEIPTHEADER_ID LEFT JOIN CUSTOMERACCOUNTS CA ON LC.CUSTOMERACCOUNT_ID=CA.CUSTOMERACCOUNT_ID WHERE LC.COMPANY_ID=ARSCHEDULEHEADER.COMPANY_ID AND (CA.CUSTOMERACCOUNT_ID IS NULL OR CA.COMPANY_ID=ARSCHEDULEHEADER.COMPANY_ID) AND UNLINKED=0)) AS CREDITONACCOUNT, (SELECT SUM(LINKEDCREDITS.LINKED_AMOUNT) AS AMOUNTLINKED FROM LINKEDCREDITS  JOIN ARSCHEDULEHEADER ARH ON ARH.ARSCHEDULEHEADER_ID = LINKEDCREDITS.ARSCHEDULEHEADER_ID WHERE LINKEDCREDITS.COMPANY_ID = ARSCHEDULEHEADER.COMPANY_ID AND LINKEDCREDITS.UNLINKED=0 AND ARH.COMPANY_ID IS NOT NULL) AS AMOUNTLINKED, (SELECT SUM(LINKEDCREDITS.LINKED_AMOUNT) AS AMOUNTLINKED FROM LINKEDCREDITS  JOIN ARSCHEDULEHEADER ARH ON ARH.ARSCHEDULEHEADER_ID = LINKEDCREDITS.ARSCHEDULEHEADER_ID WHERE LINKEDCREDITS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND LINKEDCREDITS.UNLINKED=0) AS ARSCHEDULE_AMOUNTLINKED, ((SELECT SUM(CUSTOMERACCOUNTS.AMOUNT) FROM CUSTOMERACCOUNTS WHERE CUSTOMERACCOUNTS.COMPANY_ID=COMPANIES.COMPANY_ID AND ((CUSTOMERACCOUNTS.EXPIRATIONDATE = {TS '1899-12-30 00:00:00'} OR CUSTOMERACCOUNTS.EXPIRATIONDATE >= {TS '2015-09-30 15:29:42'}) AND CUSTOMERACCOUNTS.VOIDED=0)) + (SELECT ISNULL(SUM(LC.LINKED_AMOUNT),0) FROM LINKEDCREDITS LC LEFT JOIN ARTRANSACTIONS ART ON ART.ARTRANSACTION_ID=LC.ARTRANSACTION_ID LEFT JOIN RECEIPTHEADERS RH ON RH.RECEIPTHEADER_ID=ART.RECEIPTHEADER_ID LEFT JOIN CUSTOMERACCOUNTS CA ON LC.CUSTOMERACCOUNT_ID=CA.CUSTOMERACCOUNT_ID WHERE LC.COMPANY_ID=ARSCHEDULEHEADER.COMPANY_ID AND (CA.CUSTOMERACCOUNT_ID IS NULL OR CA.COMPANY_ID=ARSCHEDULEHEADER.COMPANY_ID) AND UNLINKED=0)) AS CREDITONACCOUNT, COMPANIES.RETIRED AS RETIRED, ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID, ARSCHEDULEDETAIL.DATEDUE AS DATEDUE, (CASE WHEN ARSCHEDULEDETAIL.INITIALPAYMENT <> 0 THEN ARSCHEDULEDETAIL.AMOUNTDUE+ISNULL((SELECT SUM(ARD.AMOUNTDUE) FROM ARSCHEDULEDETAIL ARD WHERE ARD.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND ARD.VOIDED = 0 AND ARD.INITIALPAYMENT = 0 AND ARD.AMOUNTDUE < 0),0) ELSE ARSCHEDULEDETAIL.AMOUNTDUE  END) AS TOTALDUE, ARSCHEDULEHEADER.NUMBEROFPAYMENTS, ARSCHEDULEDETAIL.ARSCHEDULEDETAIL_ID, ARSCHEDULEHEADER.AUTO_PAYMENT_CC_EXP, ARSCHEDULEDETAIL.INITIALPAYMENT
FROM ARSCHEDULEHEADER "ARSCHEDULEHEADER" JOIN ARSCHEDULEDETAIL ARSCHEDULEDETAIL ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARSCHEDULEDETAIL.ARSCHEDULEHEADER_ID JOIN ARTRANSACTIONS ARTRANSACTIONS ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARTRANSACTIONS.ARSCHEDULEHEADER_ID JOIN COMPANIES COMPANIES ON ARSCHEDULEHEADER.COMPANY_ID=COMPANIES.COMPANY_ID
WHERE ARSCHEDULEHEADER.CUSTOMER_ID IN (147)
	AND (ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID IN (SELECT ARSCHEDULEHEADER_ID FROM #AGING_COMPANY_T)) AND ARSCHEDULEHEADER.VOIDED = 0 AND ARSCHEDULEDETAIL.VOIDED = 0 AND (ARSCHEDULEDETAIL.AMOUNTDUE > 0) AND ((ARSCHEDULEHEADER.AMOUNT - (SELECT CASE WHEN SUM(LINKEDCREDITS.LINKED_AMOUNT) IS NULL THEN 0 ELSE SUM(LINKEDCREDITS.LINKED_AMOUNT) END AS AMOUNTLINKED FROM LINKEDCREDITS WHERE LINKEDCREDITS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND LINKEDCREDITS.UNLINKED=0)) <> 0)
ORDER BY CLIENTTYPE, SORTNAME, ID, ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID, ARSCHEDULEDETAIL.INITIALPAYMENT, ARSCHEDULEDETAIL.DATEDUE


drop table #aging_customer_t
drop table #aging_company_t
