SELECT ISNULL(MAX(ARTRANSACTIONS.ARSCHEDULEHEADER_ID),0) AS ARSCHEDULEHEADER_ID INTO #aging_customer_t
FROM ARTRANSACTIONS "ARTRANSACTIONS" JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID JOIN CUSTOMERS CUSTOMERS ON ARTRANSACTIONS.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID
WHERE ARTRANSACTIONS.VOIDED = 0 AND ARTRANSACTIONS_1.VOIDED = 0 AND ARTRANSACTIONS.COMPANY_ID IS NULL
	AND EXISTS(SELECT * FROM ARTRANSACTIONS ART WHERE ART.ARSCHEDULEHEADER_ID = ARTRANSACTIONS.ARSCHEDULEHEADER_ID AND ART.VOIDED = 0 GROUP BY ART.ARSCHEDULEHEADER_ID HAVING SUM(ART.AMOUNT) > 0)
GROUP BY ARTRANSACTIONS.ARSCHEDULEHEADER_ID
HAVING SUM(ARTRANSACTIONS.AMOUNT) > 0

SELECT ISNULL(MAX(ARTRANSACTIONS.ARSCHEDULEHEADER_ID),0) AS ARSCHEDULEHEADER_ID INTO #aging_company_t
FROM ARTRANSACTIONS "ARTRANSACTIONS" JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID JOIN COMPANIES COMPANIES ON ARTRANSACTIONS.COMPANY_ID=COMPANIES.COMPANY_ID
WHERE ARTRANSACTIONS.VOIDED = 0 AND ARTRANSACTIONS_1.VOIDED = 0
	AND EXISTS(SELECT * FROM ARTRANSACTIONS ART WHERE ART.ARSCHEDULEHEADER_ID = ARTRANSACTIONS.ARSCHEDULEHEADER_ID AND ART.VOIDED = 0 GROUP BY ART.ARSCHEDULEHEADER_ID HAVING SUM(ART.AMOUNT) > 0)
GROUP BY ARTRANSACTIONS.ARSCHEDULEHEADER_ID
HAVING SUM(ARTRANSACTIONS.AMOUNT) > 0

DECLARE @aging_customer_company_t TABLE (CLIENTTYPE INT NOT NULL, ARSCHEDULEHEADER_ID INT NOT NULL)
INSERT INTO @aging_customer_company_t
SELECT (1) AS CLIENTTYPE, ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID
FROM ARSCHEDULEHEADER "ARSCHEDULEHEADER" JOIN ARSCHEDULEDETAIL ARSCHEDULEDETAIL ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARSCHEDULEDETAIL.ARSCHEDULEHEADER_ID
	JOIN ARTRANSACTIONS ARTRANSACTIONS ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARTRANSACTIONS.ARSCHEDULEHEADER_ID JOIN CUSTOMERS CUSTOMERS ON ARSCHEDULEHEADER.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID AND ARSCHEDULEHEADER.COMPANY_ID IS NULL
WHERE ARSCHEDULEHEADER.CUSTOMER_ID IN (131104)
	AND (ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID IN (SELECT ARSCHEDULEHEADER_ID FROM #AGING_CUSTOMER_T))
	AND ARSCHEDULEHEADER.VOIDED = 0 AND ARSCHEDULEDETAIL.VOIDED = 0
	AND (ARSCHEDULEDETAIL.AMOUNTDUE > 0)
	AND (
			ARSCHEDULEHEADER.AMOUNT
			- (
				SELECT CASE WHEN SUM(LINKEDCREDITS.LINKED_AMOUNT) IS NULL THEN 0 ELSE SUM(LINKEDCREDITS.LINKED_AMOUNT) END AS AMOUNTLINKED FROM LINKEDCREDITS
				WHERE LINKEDCREDITS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND LINKEDCREDITS.UNLINKED=0
			)
		) <> 0
UNION
SELECT (2) AS CLIENTTYPE, ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID FROM ARSCHEDULEHEADER "ARSCHEDULEHEADER" JOIN ARSCHEDULEDETAIL ARSCHEDULEDETAIL ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARSCHEDULEDETAIL.ARSCHEDULEHEADER_ID JOIN ARTRANSACTIONS ARTRANSACTIONS ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARTRANSACTIONS.ARSCHEDULEHEADER_ID JOIN COMPANIES COMPANIES ON ARSCHEDULEHEADER.COMPANY_ID=COMPANIES.COMPANY_ID WHERE ARSCHEDULEHEADER.CUSTOMER_ID IN (147) AND (ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID IN (SELECT ARSCHEDULEHEADER_ID FROM #AGING_COMPANY_T)) AND ARSCHEDULEHEADER.VOIDED = 0 AND ARSCHEDULEDETAIL.VOIDED = 0 AND (ARSCHEDULEDETAIL.AMOUNTDUE > 0) AND ((ARSCHEDULEHEADER.AMOUNT - (SELECT CASE WHEN SUM(LINKEDCREDITS.LINKED_AMOUNT) IS NULL THEN 0 ELSE SUM(LINKEDCREDITS.LINKED_AMOUNT) END AS AMOUNTLINKED FROM LINKEDCREDITS WHERE LINKEDCREDITS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND LINKEDCREDITS.UNLINKED=0)) <> 0) 

delete from #aging_customer_t
INSERT INTO #aging_customer_t SELECT DISTINCT ARSCHEDULEHEADER_ID FROM @aging_customer_company_t WHERE CLIENTTYPE = 1 ORDER BY ARSCHEDULEHEADER_ID
delete from #aging_company_t
INSERT INTO #aging_company_t SELECT DISTINCT ARSCHEDULEHEADER_ID FROM @aging_customer_company_t WHERE CLIENTTYPE = 2 ORDER BY ARSCHEDULEHEADER_ID

SELECT ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID, MAX(ARSCHEDULEHEADER.CUSTOMER_ID) AS ID, MAX(- ARSCHEDULEHEADER.CUSTOMER_ID) AS CLIENTID, MAX(1) AS CLIENTTYPE
	, CUSTOMERNAME = MAX(CUSTOMERS.LASTNAME + ', ' +CASE WHEN CUSTOMER_TITLES.DESCRIPTION IS NULL OR LEN(CUSTOMER_TITLES.DESCRIPTION) = 0 THEN '' ELSE CUSTOMER_TITLES.DESCRIPTION + ' 'END  + CUSTOMERS.FIRSTNAME + CASE WHEN CUSTOMERS.MIDDLENAME IS NULL OR LEN(CUSTOMERS.MIDDLENAME) = 0 THEN '' ELSE ' ' + CUSTOMERS.MIDDLENAME END )
	, MAX(CUSTOMERS.LASTNAME + CUSTOMERS.FIRSTNAME) AS SORTNAME, MAX(CUSTOMERS.RETIRED) AS RETIRED
	, BALANCEDUE = SUM(ARTRANSACTIONS.AMOUNT)
	, MIN(RECEIPTHEADERS.RECEIPTHEADER_ID) AS RECEIPTHEADER_ID
	, MIN(RECEIPTHEADERS.RECEIPTNUMBER) AS RECEIPTNUMBER, MIN(RECEIPTHEADERS.DATESTAMP) AS RECEIPTDATE
	, TOTALCHARGES = MAX(ARSCHEDULEHEADER.AMOUNT)
	, WITHDRAWAMOUNT = (
		SELECT ISNULL(SUM(ARTRANSACTIONS.AMOUNT), 0)
		FROM ARTRANSACTIONS
			JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID
			JOIN RECEIPTHEADERS ON RECEIPTHEADERS.RECEIPTHEADER_ID = ARTRANSACTIONS.RECEIPTHEADER_ID
			JOIN RECEIPTDETAILS RECEIPTDETAILS ON RECEIPTDETAILS.RECEIPTDETAIL_ID = ARTRANSACTIONS.RECEIPTDETAIL_ID
			JOIN TRANSACTIONS TRANSACTIONS  ON TRANSACTIONS.TRANSACTION_ID = RECEIPTDETAILS.TRANSACTION_ID
			JOIN CUSTOMERS CUSTOMERS ON ARTRANSACTIONS.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID
		WHERE ARTRANSACTIONS.VOIDED = 0 AND ARTRANSACTIONS_1.VOIDED = 0 AND ARTRANSACTIONS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID
			AND ARTRANSACTIONS.ARTRANSACTION_ID NOT IN (SELECT ARTRANSACTION_ID FROM LINK_THIRD_PARTY_BILLINGS) AND TRANSACTIONS.PERMIT_ID  IS NULL AND TRANSACTIONS.DCPROGRAM_ID IS NULL AND ARTRANSACTIONS.TRANSACTIONTYPE IN (4))
FROM ARSCHEDULEHEADER "ARSCHEDULEHEADER"
	JOIN ARTRANSACTIONS ARTRANSACTIONS ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARTRANSACTIONS.ARSCHEDULEHEADER_ID
	JOIN RECEIPTDETAILS RECEIPTDETAILS ON ARTRANSACTIONS.RECEIPTDETAIL_ID=RECEIPTDETAILS.RECEIPTDETAIL_ID
	JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID
	JOIN RECEIPTHEADERS RECEIPTHEADERS ON ARTRANSACTIONS.RECEIPTHEADER_ID=RECEIPTHEADERS.RECEIPTHEADER_ID
	LEFT JOIN TRANSACTIONS TRANSACTIONS ON RECEIPTDETAILS.TRANSACTION_ID=TRANSACTIONS.TRANSACTION_ID
	LEFT JOIN EQUIPMENTLENDINGTRANSACTIONS EQUIPMENTLENDINGTRANSACTIONS ON TRANSACTIONS.TRANSACTION_ID=EQUIPMENTLENDINGTRANSACTIONS.TRANSACTION_ID
	JOIN CUSTOMERS CUSTOMERS ON ARSCHEDULEHEADER.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID
	LEFT JOIN CUSTOMER_TITLES CUSTOMER_TITLES ON CUSTOMER_TITLES.CUSTOMER_TITLE_ID=CUSTOMERS.CUSTOMER_TITLE_ID
WHERE ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID IN (SELECT ARSCHEDULEHEADER_ID FROM #AGING_CUSTOMER_T)
	AND ARSCHEDULEHEADER.CUSTOMER_ID IN (147)
	AND ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID IN (
		SELECT ARSCHEDULEHEADER_ID FROM ARSCHEDULEDETAIL "ARSCHEDULEDETAIL" WHERE VOIDED = 0 AND AMOUNTDUE > 0 AND ARSCHEDULEDETAIL.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID GROUP BY ARSCHEDULEHEADER_ID
	)
	AND ARTRANSACTIONS.VOIDED = 0 AND ARTRANSACTIONS_1.VOIDED = 0 AND RECEIPTDETAILS.VOIDED = 0
GROUP BY ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID
UNION SELECT ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID, MAX(ARSCHEDULEHEADER.COMPANY_ID) AS ID, MAX(ARSCHEDULEHEADER.COMPANY_ID) AS CLIENTID, ISNULL(MAX(2),0) AS CLIENTTYPE, MAX(COMPANIES.COMPANYNAME) AS CUSTOMERNAME, MAX(COMPANIES.COMPANYNAME) AS SORTNAME, MAX(COMPANIES.RETIRED) AS RETIRED, SUM(ARTRANSACTIONS.AMOUNT) AS BALANCEDUE, MIN(RECEIPTHEADERS.RECEIPTHEADER_ID) AS RECEIPTHEADER_ID, MIN(RECEIPTHEADERS.RECEIPTNUMBER) AS RECEIPTNUMBER, MIN(RECEIPTHEADERS.DATESTAMP) AS RECEIPTDATE, MAX(ARSCHEDULEHEADER.AMOUNT) AS TOTALCHARGES, (SELECT ISNULL(SUM(ARTRANSACTIONS.AMOUNT), 0) FROM ARTRANSACTIONS JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID  JOIN RECEIPTHEADERS ON RECEIPTHEADERS.RECEIPTHEADER_ID = ARTRANSACTIONS.RECEIPTHEADER_ID   JOIN RECEIPTDETAILS RECEIPTDETAILS ON RECEIPTDETAILS.RECEIPTDETAIL_ID = ARTRANSACTIONS.RECEIPTDETAIL_ID    JOIN TRANSACTIONS TRANSACTIONS  ON TRANSACTIONS.TRANSACTION_ID = RECEIPTDETAILS.TRANSACTION_ID   JOIN COMPANIES COMPANIES ON ARTRANSACTIONS.COMPANY_ID=COMPANIES.COMPANY_ID  WHERE ARTRANSACTIONS.VOIDED = 0 AND ARTRANSACTIONS_1.VOIDED = 0 AND ARTRANSACTIONS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND ARTRANSACTIONS.ARTRANSACTION_ID NOT IN (SELECT ARTRANSACTION_ID FROM LINK_THIRD_PARTY_BILLINGS) AND TRANSACTIONS.PERMIT_ID  IS NULL AND TRANSACTIONS.DCPROGRAM_ID IS NULL AND ARTRANSACTIONS.TRANSACTIONTYPE IN (4)) AS WITHDRAWAMOUNT FROM ARSCHEDULEHEADER "ARSCHEDULEHEADER" JOIN ARTRANSACTIONS ARTRANSACTIONS ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARTRANSACTIONS.ARSCHEDULEHEADER_ID JOIN RECEIPTDETAILS RECEIPTDETAILS ON ARTRANSACTIONS.RECEIPTDETAIL_ID=RECEIPTDETAILS.RECEIPTDETAIL_ID JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID JOIN RECEIPTHEADERS RECEIPTHEADERS ON ARTRANSACTIONS.RECEIPTHEADER_ID=RECEIPTHEADERS.RECEIPTHEADER_ID LEFT JOIN TRANSACTIONS TRANSACTIONS ON RECEIPTDETAILS.TRANSACTION_ID=TRANSACTIONS.TRANSACTION_ID LEFT JOIN EQUIPMENTLENDINGTRANSACTIONS EQUIPMENTLENDINGTRANSACTIONS ON TRANSACTIONS.TRANSACTION_ID=EQUIPMENTLENDINGTRANSACTIONS.TRANSACTION_ID JOIN COMPANIES COMPANIES ON ARSCHEDULEHEADER.COMPANY_ID=COMPANIES.COMPANY_ID WHERE ARSCHEDULEHEADER.CUSTOMER_ID IN (147) AND (ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID IN (SELECT ARSCHEDULEHEADER_ID FROM #AGING_COMPANY_T)) AND ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID IN (SELECT ARSCHEDULEHEADER_ID FROM ARSCHEDULEDETAIL "ARSCHEDULEDETAIL" WHERE VOIDED = 0 AND AMOUNTDUE > 0 AND ARSCHEDULEDETAIL.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID GROUP BY ARSCHEDULEHEADER_ID) AND ARTRANSACTIONS.VOIDED = 0 AND ARTRANSACTIONS_1.VOIDED = 0 AND RECEIPTDETAILS.VOIDED = 0 GROUP BY ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID
ORDER BY CLIENTTYPE, SORTNAME, ID, ARSCHEDULEHEADER_ID


drop table #aging_customer_t
drop table #aging_company_t