SELECT PACKAGES.PACKAGENAME, PACKAGES.PACKAGE_ID, MEMBERSHIPS.DATESOLD, MEMBERSHIPS.DATEEFFECTIVE, MEMBERSHIPS.DATEEXPIRES, MEMBERSHIPS.STATUS, MEMBERSHIPS.AUTORENEWALTYPE, MEMBERSHIPS.AUTORENEWALSTATUS, MEMBERSHIPS.AUTORENEWALACCEPTANCEDATE, MEMBERSHIPS.MEMBERSHIP_ID, MEMBERSHIPS.PRIMARYMEMBERCUSTOMER_ID, CUSTOMERS.CUSTOMER_ID
	, CASE WHEN CUSTOMERS.MAILING_NAME IS NULL OR LEN(CUSTOMERS.MAILING_NAME)=0 THEN (CUSTOMERS.LASTNAME + ', ' + CUSTOMERS.FIRSTNAME) ELSE CUSTOMERS.MAILING_NAME END AS MEMBERNAME
	, (CUSTOMERS.ADDRESS1 + ' ' + CUSTOMERS.ADDRESS2) AS 'Address', (CUSTOMERS.CITY + ', ' + CUSTOMERS.STATE + ' ' + CUSTOMERS.ZIPCODE) AS 'CityStateZip', CUSTOMERS.GENDER, CUSTOMERS.RESIDENT, CUSTOMERS.BIRTHDATE, CUSTOMERS.HOMEPHONE, CUSTOMERS.WORKPHONE, CUSTOMERS.CELLPHONE, MAX(TRANSACTION_ID) AS TRANSACTION_ID, MAX(RECEIPTHEADERS.TOTALFEE) AS TOTALFEE
FROM MEMBERSHIPS "MEMBERSHIPS" JOIN MEMBERSHIP_PASSES MEMBERSHIP_PASSES ON MEMBERSHIP_PASSES.MEMBERSHIP_ID=MEMBERSHIPS.MEMBERSHIP_ID JOIN PASSES PASSES ON MEMBERSHIP_PASSES.PASS_ID=PASSES.PASS_ID
	JOIN CUSTOMERS CUSTOMERS ON PASSES.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID JOIN PACKAGES PACKAGES ON MEMBERSHIPS.PACKAGE_ID=PACKAGES.PACKAGE_ID JOIN PACKAGE_FEES PACKAGE_FEES ON PACKAGE_FEES.PACKAGE_ID=PACKAGES.PACKAGE_ID
	JOIN TRANSACTIONS TRANSACTIONS ON MEMBERSHIPS.MEMBERSHIP_ID=TRANSACTIONS.MEMBERSHIP_ID JOIN RECEIPTHEADERS RECEIPTHEADERS ON TRANSACTIONS.RECEIPTHEADER_ID=RECEIPTHEADERS.RECEIPTHEADER_ID
WHERE EXISTS(SELECT MEMBERSHIP_ID FROM MEMBERSHIPAUTORENEWAL WHERE MEMBERSHIP_ID = MEMBERSHIPS.MEMBERSHIP_ID )
	AND (MEMBERSHIPS.AUTORENEWALACCEPTANCEDATE>={TS '2016-01-13 00:00:00'} AND MEMBERSHIPS.AUTORENEWALACCEPTANCEDATE<{D '2016-01-16'})
	AND CUSTOMERS.CUSTOMER_ID IN (199)
	AND TRANSACTIONS.TRANSACTIONTYPE = 33
	AND NOT MEMBERSHIPS.STATUS IN (3,4)
GROUP BY PACKAGES.PACKAGENAME, PACKAGES.PACKAGE_ID, MEMBERSHIPS.DATESOLD, MEMBERSHIPS.DATEEFFECTIVE, MEMBERSHIPS.DATEEXPIRES, MEMBERSHIPS.STATUS, MEMBERSHIPS.AUTORENEWALTYPE, MEMBERSHIPS.AUTORENEWALSTATUS, MEMBERSHIPS.AUTORENEWALACCEPTANCEDATE, MEMBERSHIPS.MEMBERSHIP_ID, MEMBERSHIPS.PRIMARYMEMBERCUSTOMER_ID, CUSTOMERS.CUSTOMER_ID, CUSTOMERS.LASTNAME, CUSTOMERS.FIRSTNAME,CUSTOMERS.MAILING_NAME, CUSTOMERS.ADDRESS1, CUSTOMERS.ADDRESS2, CUSTOMERS.CITY, CUSTOMERS.STATE, CUSTOMERS.ZIPCODE, CUSTOMERS.GENDER, CUSTOMERS.RESIDENT, CUSTOMERS.BIRTHDATE, CUSTOMERS.HOMEPHONE, CUSTOMERS.WORKPHONE, CUSTOMERS.CELLPHONE
ORDER BY CUSTOMERS.LASTNAME, CUSTOMERS.FIRSTNAME, MEMBERSHIPS.MEMBERSHIP_ID

