SELECT ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID, CUSTOMERS.CUSTOMER_ID, CUSTOMERS.EMAIL, CUSTOMERS.ADDITIONAL_EMAIL
	, CUSTOMERNAME = CASE WHEN CUSTOMER_TITLES.DESCRIPTION IS NULL OR LEN(CUSTOMER_TITLES.DESCRIPTION) = 0 THEN '' ELSE CUSTOMER_TITLES.DESCRIPTION + ' 'END + CUSTOMERS.FIRSTNAME + ' ' + CASE WHEN CUSTOMERS.MIDDLENAME IS NULL OR LEN(CUSTOMERS.MIDDLENAME) = 0 THEN '' ELSE CUSTOMERS.MIDDLENAME + ' ' END + CUSTOMERS.LASTNAME
	, COMPANIES.COMPANY_ID, COMPANIES.COMPANYNAME, COMPANIES.EMAIL AS COMPANYEMAIL, ARSCHEDULEHEADER.DATECREATED, ARSCHEDULEHEADER.NUMBEROFPAYMENTS, ARSCHEDULEHEADER.BILLINGTYPE
	, ARSCHEDULEHEADER.FIRSTPAYMENT, RECEIPTHEADERS.RECEIPTNUMBER, ARSCHEDULEDETAIL.AMOUNTDUE, ARSCHEDULEDETAIL.DATEDUE, ARSCHEDULEHEADER.AUTO_PAYMENT_TYPE, ARSCHEDULEHEADER.AUTO_PAYMENT_ACCOUNT
	, ARSCHEDULEDETAIL.ARSCHEDULEDETAIL_ID
	, AMOUNTOWED = (SELECT SUM(ARTRANSACTIONS.AMOUNT) FROM ARTRANSACTIONS "ARTRANSACTIONS" JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID JOIN RECEIPTDETAILS RECEIPTDETAILS ON ARTRANSACTIONS_1.RECEIPTDETAIL_ID=RECEIPTDETAILS.RECEIPTDETAIL_ID JOIN TRANSACTIONS TRANSACTIONS ON RECEIPTDETAILS.TRANSACTION_ID=TRANSACTIONS.TRANSACTION_ID WHERE ARTRANSACTIONS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND (ARTRANSACTIONS.VOIDED = 0) AND (ARTRANSACTIONS_1.VOIDED = 0) AND (ARTRANSACTIONS.TRANSACTIONTYPE IN (1,2,3,8) OR (ARTRANSACTIONS.TRANSACTIONTYPE=6 AND ARTRANSACTIONS.AMOUNT > 0)) AND NOT EXISTS( SELECT * FROM TRANSACTIONS TR WHERE TRANSACTIONS.ORIGINALTRANSACTION_ID = TR.ORIGINALTRANSACTION_ID AND TR.TRANSACTIONTYPE = 39))
	, AMOUNTPAID = (SELECT SUM(-ARTRANSACTIONS.AMOUNT) AS AMOUNTPAID FROM ARTRANSACTIONS "ARTRANSACTIONS" JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID JOIN RECEIPTDETAILS RECEIPTDETAILS ON ARTRANSACTIONS_1.RECEIPTDETAIL_ID=RECEIPTDETAILS.RECEIPTDETAIL_ID JOIN TRANSACTIONS TRANSACTIONS ON RECEIPTDETAILS.TRANSACTION_ID=TRANSACTIONS.TRANSACTION_ID WHERE ARTRANSACTIONS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND (ARTRANSACTIONS.VOIDED = 0) AND (ARTRANSACTIONS_1.VOIDED = 0) AND ARTRANSACTIONS.TRANSACTIONTYPE IN (5,6,7,9,10) AND ARTRANSACTIONS.AMOUNT < 0 AND NOT EXISTS( SELECT * FROM TRANSACTIONS TR WHERE TRANSACTIONS.ORIGINALTRANSACTION_ID = TR.ORIGINALTRANSACTION_ID AND TR.TRANSACTIONTYPE = 39))
	, SUMAMOUNTPAIDBEFOREDUEDATE = (SELECT ISNULL(SUM(ARSCHEDULEDETAIL_BEFORE.AMOUNTDUE),0) FROM ARSCHEDULEDETAIL "ARSCHEDULEDETAIL_BEFORE" JOIN ARSCHEDULEHEADER ARSCHEDULEHEADER_BEFORE ON ARSCHEDULEDETAIL_BEFORE.ARSCHEDULEHEADER_ID=ARSCHEDULEHEADER_BEFORE.ARSCHEDULEHEADER_ID WHERE ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARSCHEDULEHEADER_BEFORE.ARSCHEDULEHEADER_ID AND ARSCHEDULEDETAIL_BEFORE.ARSCHEDULEDETAIL_ID < ARSCHEDULEDETAIL.ARSCHEDULEDETAIL_ID AND ARSCHEDULEDETAIL_BEFORE.VOIDED=0)
	, AMOUNTWITHDRAW = (SELECT SUM(-ARTRANSACTIONS.AMOUNT) AS AMOUNTWITHDRAW FROM ARTRANSACTIONS "ARTRANSACTIONS" JOIN ARTRANSACTIONS ARTRANSACTIONS_1 ON ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS_1.ARTRANSACTION_ID JOIN RECEIPTDETAILS RECEIPTDETAILS ON ARTRANSACTIONS.RECEIPTDETAIL_ID=RECEIPTDETAILS.RECEIPTDETAIL_ID JOIN TRANSACTIONS TRANSACTIONS ON RECEIPTDETAILS.TRANSACTION_ID=TRANSACTIONS.TRANSACTION_ID WHERE ARTRANSACTIONS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND (ARTRANSACTIONS.VOIDED = 0) AND (ARTRANSACTIONS_1.VOIDED = 0) AND ARTRANSACTIONS.TRANSACTIONTYPE IN (4) AND (((SELECT COUNT(*) FROM TRANSACTIONS WHERE ROOTTRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRANSACTIONS WHERE RECEIPTHEADER_ID = RECEIPTHEADERS.RECEIPTHEADER_ID) AND TRANSACTIONTYPE = 32) <= 0 ) OR (((SELECT COUNT(*) FROM TRANSACTIONS WHERE ROOTTRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRANSACTIONS WHERE RECEIPTHEADER_ID = RECEIPTHEADERS.RECEIPTHEADER_ID) AND TRANSACTIONTYPE = 32) > 0 ) OR (((ARTRANSACTIONS.COMPANY_ID > 0 AND ARTRANSACTIONS.ARTRANSACTION_ID NOT IN (SELECT ARTRANSACTION_ID FROM LINK_THIRD_PARTY_BILLINGS)) OR (ARTRANSACTIONS.CUSTOMER_ID > 0))))) AND NOT EXISTS( SELECT * FROM TRANSACTIONS TR WHERE TRANSACTIONS.ORIGINALTRANSACTION_ID = TR.ORIGINALTRANSACTION_ID AND TR.TRANSACTIONTYPE = 39))
	, AMOUNTLINKED = (SELECT ISNULL(SUM(LINKEDCREDITS.LINKED_AMOUNT),0) AS AMOUNTLINKED FROM LINKEDCREDITS "LINKEDCREDITS" LEFT JOIN ARSCHEDULEHEADER ARSH ON ARSH.ARSCHEDULEHEADER_ID=LINKEDCREDITS.ARSCHEDULEHEADER_ID LEFT JOIN ARTRANSACTIONS ARTR ON ARTR.ARTRANSACTION_ID=LINKEDCREDITS.ARTRANSACTION_ID WHERE ARSH.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID AND LINKEDCREDITS.UNLINKED=0 AND (ARTR.VOIDED = 0))
	, NULL AS DCSESSIONNAME
FROM ARSCHEDULEHEADER
	LEFT JOIN CUSTOMERS ON ARSCHEDULEHEADER.CUSTOMER_ID=CUSTOMERS.CUSTOMER_ID
	LEFT JOIN CUSTOMER_TITLES ON CUSTOMER_TITLES.CUSTOMER_TITLE_ID=CUSTOMERS.CUSTOMER_TITLE_ID
	LEFT JOIN COMPANIES ON ARSCHEDULEHEADER.COMPANY_ID=COMPANIES.COMPANY_ID
	JOIN RECEIPTPAYMENTS ON RECEIPTPAYMENTS.RECEIPTPAYMENT_ID=ARSCHEDULEHEADER.RECEIPTPAYMENT_ID
	JOIN RECEIPTHEADERS ON RECEIPTHEADERS.RECEIPTHEADER_ID=RECEIPTPAYMENTS.RECEIPTHEADER_ID
	LEFT JOIN ARSCHEDULEDETAIL ON ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID=ARSCHEDULEDETAIL.ARSCHEDULEHEADER_ID
WHERE (ARSCHEDULEHEADER.VOIDED = 0)
	AND (ARSCHEDULEDETAIL.VOIDED = 0)
	AND ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID IN (
		SELECT ARSCHEDULEHEADER_ID FROM ARSCHEDULEDETAIL WHERE (ARSCHEDULEDETAIL.DATEDUE<{D '2016-08-23'})
	)
	AND EXISTS(
		SELECT ARTRANSACTIONS.ARTRANSACTION_ID
		FROM ARTRANSACTIONS
			JOIN RECEIPTDETAILS ON ARTRANSACTIONS.RECEIPTDETAIL_ID=RECEIPTDETAILS.RECEIPTDETAIL_ID
			JOIN TRANSACTIONS ON RECEIPTDETAILS.TRANSACTION_ID=TRANSACTIONS.TRANSACTION_ID
		WHERE ARTRANSACTIONS.ARSCHEDULEHEADER_ID = ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID
			AND TRANSACTIONS.TRANSACTIONTYPE NOT IN (6,7,8,20,67,87)
			AND (ARTRANSACTIONS.ORIGINALARTRANSACTION_ID IS NULL OR ARTRANSACTIONS.ORIGINALARTRANSACTION_ID=ARTRANSACTIONS.ARTRANSACTION_ID)
	)
	AND (ARSCHEDULEDETAIL.DATEDUE<{D '2016-08-23'})
	--and CUSTOMERS.CUSTOMER_ID = 261
ORDER BY CUSTOMERS.LASTNAME, CUSTOMERS.FIRSTNAME, CUSTOMERS.CUSTOMER_ID, COMPANIES.COMPANYNAME, COMPANIES.COMPANY_ID, ARSCHEDULEHEADER.DATECREATED
	, ARSCHEDULEHEADER.ARSCHEDULEHEADER_ID, ARSCHEDULEDETAIL.INITIALPAYMENT, ARSCHEDULEDETAIL.DATEDUE