/*
SELECT * FROM CUSTOMERS WHERE LASTNAME = 'TransactionChain'
*/

DECLARE @receiptnumber money
DECLARE @receiptheader_id int
DECLARE @transaction_id int
SET @receiptnumber = 1000302.002
SET @receiptheader_id = (SELECT RECEIPTHEADER_ID FROM RECEIPTHEADERS WHERE RECEIPTNUMBER = @receiptnumber)
SELECT * FROM RECEIPTHEADERS where RECEIPTHEADER_ID = @receiptheader_id
SELECT * FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id
SELECT * FROM RECEIPTDETAILS WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM TRANSACTIONS where RECEIPTHEADER_ID = @receiptheader_id) ORDER BY RECEIPTDETAIL_ID
SELECT * FROM RECEIPTPAYMENTS WHERE RECEIPTHEADER_ID = @receiptheader_id
SELECT * FROM DBO.ARTRANSACTIONS with(nolock) where RECEIPTHEADER_ID = @receiptheader_id

SELECT * FROM ARSCHEDULEHEADER WHERE RECEIPTPAYMENT_ID = 6655
SELECT * FROM ARSCHEDULEDETAIL WHERE ARSCHEDULEHEADER_ID = 3094
